server:
  port: 8006

#入住eureka server 的服务名称
spring:
  application:
    name: cloud-payment-service #服务名称
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: 192.168.124.5
        service-name: ${spring.application.name}
