server:
  port: 80
spring:
  application:
    name: cloud-provider-hystrix-payment
eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

feign:
  hystrix:
    enabled: true